name: Auto Release

on:
  push:
    paths:
    - 'version.txt'
  
permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Version Date
        run: |
          echo "RELEASE_VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ env.RELEASE_VERSION }}
          tag_exists_error: true
          message: "Latest release"
      
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: ${{ env.RELEASE_VERSION }}
